version: '2'
services:
  frontend:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - demo:/var/lib/mysql/
volumes:
  demo:
